### ISSUE TITLE
Part orientation when installing

### ISSUE THREAD

**Issue by mvdveer** [Ramalama2/Voron-2-Mods#10]
Doing a new 2.4r2 build. Some observations: Printed really well - followed instructions on Github re assembly - no issues at all. When installing the idlers on Y on a new build, following the manual, it may be confusing for newbies as the original idlers have 2 x 5mm holes on the top and a 5mm and 3 mm on the bottom, which allows for easy orientation (as per the manual). This mod has a 5mm and 3mm on both top and bottom and pully orientation may be tricky. As it is still in Beta, this may be something to consider.

**Comment by Ramalama2** [comment]
Hi, on the voron 2.4, there is no need for any orientation, since you can mount them only "correct". It's the same housing for left/right.

On the Trident, i made a small hole thingy on the bottom, so that you "know" the orientation. Just don't remember if i mentioned it somewhere 🙈

The holes are intented to be same on top/bottom.
There are 2 reasons for that.
1. Some people use linear rails at the top as backers, with 2xM5 holes they won't fit.
2. On the 2.4 you don't need 2 different housings (you would need if the top had different holes as the bottom), that means additionally that you aren't able to mount them wrong.

Sry, im a bit late with replying, feel free to close the issue if it's solved 😂
Cheers

**Comment by mvdveer** [comment]
Thanks for the clarification, fully understand your rationale.  I fitted them without a problem, was just an observation relating to the manual . 

Great mod. 

Hope to see it in the next Voron 2.4 release.
