### ISSUE TITLE
GE5C version

### ISSUE THREAD

**Issue by EricZimmerman** [Ramalama2/Voron-2-Mods#14]
Are the left and right portions of these:

https://github.com/Ramalama2/Voron-2-Mods/tree/main/Front_Idlers/Voron%202.4/STL/Alternatives/GE5C_Version

going to work with the default inlets:

https://github.com/Ramalama2/Voron-2-Mods/blob/main/Front_Idlers/Voron%202.4/STL/Front-Idlers_Inlet-5.15mm_default.stl

the description says to simply print things 2x, but the GE5Cs mention a left and right. why is that?

just want to make sure i have what i need before install.

thanks!

**Comment by EricZimmerman** [comment]
Nothing on this? The parts can really use a good round of documentation as to what works for what and why you would want different things.

**Comment by blownupp** [comment]
I’d like to second this - for the life of me I can’t tell the difference between the L and R pieces

**Comment by Ramalama2** [comment]
> the description says to simply print things 2x, but the GE5Cs mention a left and right. why is that?


> I’d like to second this - for the life of me I can’t tell the difference between the L and R pieces

- The difference In the L & R Part is, that the Big hole on the bottom side (where the ge5c joint is attached) is not round, instead it is Oval:
![ana-01en](https://user-images.githubusercontent.com/6314556/235962362-8bde929b-bbe4-4711-954b-f2442b1f45fc.png)

Just to allow a wiggle room for the ge5c joint of 0,5mm.

There is a but: No one uses that, even hartk itself uses the non ge5c version.
What i mean is, it fits perfectly fine if you simply use the non ge5c version, but if you use the ge5c version, it will simply fit slightly better.
0.5mm doesn't make a lot of difference tbh, if any at all.
I just provide that version, because hartk does it either on his github xD

Cheers
