### ISSUE TITLE
LGX Lite for ERCF filament sensor

### ISSUE THREAD

**Issue by Jaans** [Ramalama2/Voron-2-Mods#17]
Hi Rama,

Thank you for the amazing work you guys have been doing with this. 

Are there any plans to make the same modifications to the ERCF version of the LGX Lite model from Eytecz?

Alternatively, are you able to describe the relevant changes you've made? 
That way I can try to repeat them myself on the ERCF version from Eytecz's models.

Thanks, Jaans.

PS: I know there is an ERCF branch with StallGuard to provide an option to not need the toolhead filament sensor, but that doesn't suit me.

**Comment by Ramalama2** [comment]
Hey, sorry for the Late reply.
- I wont make any changes  anymore, basically i dont make any Voron mods at all anymore xD
- The changes, ughhh that was so long ago, i dont remember even what i did, but actually not much. As far i remember i did initially this "Mod", because at the time, Eytecz didn't hat an option for the Hartk PCB and afterwards i remember that i modified everything a little bit, to make the mount Stiffer.
- But that changed, Eytecz has an Hart-PCB & Ercf + PCB Version now and i see no reasons to Stay on my Version actually.

Cheers :-)
