### ISSUE TITLE
SB_LGXlitePCB - Cable Cover Test1 Doesn't Fit With Connector Plugs

### ISSUE THREAD

**Issue by D1rect10ns** [Ramalama2/Voron-2-Mods#20]
Feedback on the cable cover test1. It fits perfectly without the probe, FS, main 14-pin plug, or led plugs connected into the board, however with those connectors plugged in the cable cover won't close. It printed fine and doesn't seem too thin.

Thanks for the great projects Ramalama2! Lovin' your work!

**Comment by Ramalama2** [comment]
Np, i know that the cover doesn't fit, just dunno if i should delete it or not, if ill delete it, then ill take away the opportunity to fix the Cover a little.
Dunno, but i definitively wont do a proper one, because it makes simply no sense for me.
One one hand im doing a whole new printer for myself, that will be not attractive to anyone, because it will be expensive as fuck.
On the other side i've realized that the LGX Lite isn't as nice/good as i hoped initially as i made this "Mod"...
I cant even say that ive made this mod, because its just a modification actually of Eytecz one...

Im anyway out of Voron Mods or Voron in general. As everyone already realized xD
But thanks for the Kudos :-)
