### ISSUE TITLE
Define brush location

### ISSUE THREAD

**Issue by rmilyard** [Ramalama2/Voron-2-Mods#25]
I am looking at the Macro for Decontaminator Purge Bucket & Nozzle Scrubber.  I have my brush at rear (y) and center (x).  Not sure in marco how I change scrub location.

**Comment by Ramalama2** [comment]
But its defined in his Macro, even with a picture.
[macro-purgebucket.cfg.zip](https://github.com/Ramalama2/Voron-2-Mods/files/11384452/macro-purgebucket.cfg.zip)

Thats my slightly modified macro for my 350.
But no one should use it as it is, you have to adjust the variables anyway, because everyones Y is different, even if the brush itself is perfectly centered.
Even while the Brush itself is perfectly centered, everyones center is different either, because of the endstop tolerances/endstop variations.

Cheers
