### ISSUE TITLE
Clarify number of Z-Belt-Clamps needed for the Front Idlers

### ISSUE THREAD

**Issue by scul86** [Ramalama2/Voron-2-Mods#30]
The filename of the `Front-Idlers_Z-Belt-Clamp-Upper-Left_x2` and `Front-Idlers_Z-Belt-Clamp-Upper-Right_x2` suggest that 2 of each should be printed, but then the instructions only seem to mention 2 of the modified clamps are required (1 each of left and right).

**Comment by Ramalama2** [comment]
That depends on the version you're using, the normal version which i recommend, uses both 2x

The alternative ge5c Version, is different. But i thought i mentioned it somewhere. I think that's what you mean with the instructions.

**Comment by scul86** [comment]
Yea, normal idlers, not the ge5c version.

By instructions, I meant the `Explosion_v2.pdf`.  That file specifies for each idler:  
- 1x stock Voron lower clamp  
- 1x top clip provided in this repository.  

I would assume the "provided clip" to be 1x of the `Front-Idlers_Z-Belt-Clamp-Upper-[Left|Right]_x2.stl` depending on which side that idler is intended for.  
I just don't see where the second clamp (specified in the filename w/ ***x2***) would go.

What makes sense in my mind for the full gantry would be:
- 4x stock Voron lower clamp
- 2x stock Voron upper clamp (for A/B motor mounts)
- 1x Front-Idlers_Z-Belt-Clamp-Upper-Left_x2.stl
- 1x Front-Idlers_Z-Belt-Clamp-Upper-Right_x2.stl

Is my above assumption wrong?  I am about to start my first v2.4 build, so I've not been able to try various combinations.

**Comment by Ramalama2** [comment]
Aaah, yeah i was a bit stupid after 2 years xD

4x stock Voron lower clamp
2x stock Voron upper clamp (for A/B motor mounts)
1x Front-Idlers_Z-Belt-Clamp-Upper-Left.stl
1x Front-Idlers_Z-Belt-Clamp-Upper-Right.stl

Additionally:
2x Front-Idlers_Housing-Cover.stl
2x Front-Idlers_Housing_30mmScrew.stl
2x Front-Idlers_Inlet-5.15mm_default.stl
2x Beta_Cover_Round.stl (or round or henrikkson etc)
That is correct.

But i would exchange the normal versions there with the nipplefix variant (the reason is, the nipples on the normal version can brake easily). If they brake that's not a big deal either, but not beautiful xD
So:
2x Nipplefix-Front-Idlers_Housing_30mmScrew.stl
2x Nipplefix-Front-Idlers_Housing-Cover.stl

However you said:
"I just don't see where the second clamp (specified in the filename w/ x2) would go."
"Front-Idlers_Z-Belt-Clamp-Upper-Left_x2.stl"

Where do you see that filename? There is no filename with _x2 in the end...

**Comment by scul86** [comment]
Huh, strange... Could have sworn they were in the filenames that I cloned from this repo.  Should have double checked the live repo first.

I'll have to double check tomorrow when I get home.

**Comment by scul86** [comment]
yea, no idea where that `_x2` came from in my copies of the files.  I don't remember changing them, but must have.  

Re-cloned the repo to a new location, and there were no `_x2` designations.
